### ISSUE TITLE
Error:(40, 13) Failed to resolve: com.beust:klaxon:2.1.3 

### ISSUE THREAD

**Issue by Yash463** [cbeust/klaxon#102]
Error:(40, 13) Failed to resolve: com.beust:klaxon:2.1.3

**Comment by whittid4** [comment]
I am getting the same. `compile 'com.beust:klaxon:2.0.11'` seems to work though and looking at the releases tab 2.0.11 is the latest release

**Comment by cbeust** [comment]
2.1.2 is the latest right now.

How did you get this error, @Yash463 ?

**Comment by Yash463** [comment]
I got this when i added it as dependencies in gradle.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Cedric Beust <notifications@github.com> Date: 1/31/18  9:27 PM  (GMT+05:30) To: cbeust/klaxon <klaxon@noreply.github.com> Cc: Yashwant <yash463@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [cbeust/klaxon] Error:(40, 13) Failed to resolve:
  com.beust:klaxon:2.1.3 (#102) 
2.1.2 is the latest right now.
How did you get this error, @Yash463 ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cbeust/klaxon","title":"cbeust/klaxon","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cbeust/klaxon"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cbeust in #102: 2.1.2 is the latest right now.\r\n\r\nHow did you get this error, @Yash463 ?"}],"action":{"name":"View Issue","url":"https://github.com/cbeust/klaxon/issues/102#issuecomment-361977389"}}}

**Comment by cbeust** [comment]
You probably don't have JCenter listed as a repo?

(by the way, 2.1.4 is the latest now:  http://jcenter.bintray.com/com/beust/klaxon/2.1.4/ )
