### ISSUE TITLE
Klaxon().parse<T>(jsonString)

### ISSUE THREAD

**Issue by Yash463** [cbeust/klaxon#104]
Klaxon().parse<T>(jsonString)

Showing this error : Cannot use 'T' as reified type parameter. Use a class instead

How we can do this. Where T is the generic.Could you please let me know if Klaxon provide this functionality or not.

**Comment by cbeust** [comment]
Missing code?

**Comment by Yash463** [comment]
class JsonParser <T>{
    
        fun parseJsonStringUsingKlaxon(jsonString: String): T? {
            var response: T?= null
            response = parseJsonStringToTemplateObject(jsonString)
            return response;
        }

        fun parseJsonStringToTemplateObject(jsonString: String): T? {
            try {
                val response = Klaxon().parse<T>(jsonString)
                return response
            } catch(e: Exception) {
                return null
            }
        }
}

**Comment by cbeust** [comment]
The function needs to be `inline reified`:

```
    inline fun <reified T> parseJsonStringUsingKlaxon(jsonString: String): T? {
        val response = Klaxon().parse<T>(jsonString)
        return response;
    }
```
