### ISSUE TITLE
escapeString should escape '

### ISSUE THREAD

**Issue by vishna** [cbeust/klaxon#108]
Render probably needs an extra line [here](https://github.com/cbeust/klaxon/blob/2c277964f6a79406315947147d1660d60b16fe8e/src/main/kotlin/com/beust/klaxon/Render.kt#L31):
```kotlin
'\'' -> append("\\").append(ch)
```

**Comment by cbeust** [comment]
Actually this change broke a test:

```
    fun objectQuote() {
        jsonEquals("{ \"v\":\"ab'c\"}", "{\"v\":\"ab'c\"}")
    }
```

Can you point me to the JSON spec part that says quotes should be escaped?

**Comment by vishna** [comment]
yeah, makes sense - I was trying to use google translate API - and for whatever reason they had a single quoted json (although they updated the docs now and it's part of curl command) https://cloud.google.com/translate/docs/translating-text

the json looked like this:
```
{
  'q': 'Hello world',
  'q': 'My name is Jeff',
  'target': 'de'
}
```

FYI sending json formatted like this works for translation API - so I though I was doing everything right.

Obviously I couldn't generate the above json with Klaxon because of multiple keys being q, but I could reuse the escapeString method which I did and since it's single quoted, it needed ' escaped. Sorry for the wrong fix.
