### ISSUE TITLE
javascript target instructions?

### ISSUE THREAD

**Issue by raould** [cbeust/klaxon#111]
hi, clueless Kotlin newbie here, I'd like to try out this library with a Kotlin-targeting-JavaScript project, not a Java one. So my Intellij created Kotlin project does not use gradle afaict. How might I be able to plug this into my existing test project? thanks for any pointers.

**Comment by cbeust** [comment]
What is your other project building with?

**Comment by raould** [comment]
Whatever automagic Kotlin-in-IntelliJ does by default when I make a new Kotlin-JS project via the IntelliJ project setup wizard. There's a .iml file in the project directory fwiw. Presumably this is overall more of a (so-called) JetBrains question than really a question for you, but I hoped maybe you or somebody else had used Klaxon to target JS already.


```
<?xml version="1.0" encoding="UTF-8"?>
<module type="JAVA_MODULE" version="4">
  <component name="NewModuleRootManager" inherit-compiler-output="true">
    <exclude-output />
    <content url="file://$MODULE_DIR$">
      <sourceFolder url="file://$MODULE_DIR$/src" isTestSource="false" />
    </content>
    <orderEntry type="inheritedJdk" />
    <orderEntry type="sourceFolder" forTests="false" />
    <orderEntry type="library" name="KotlinJavaScript" level="project" />
  </component>
</module>
```

**Comment by cbeust** [comment]
Not really a Klaxon question...
