### ISSUE TITLE
Klaxon errors on delegated properties

### ISSUE THREAD

**Issue by hughartk** [cbeust/klaxon#114]
Given the following definitions:

```Kotlin
interface Foo{ val x: Int }
data class FooImpl(override val x: Int): Foo
data class BarImpl(val y: Int, val foo: FooImpl): Foo by foo
```

Creating a JSON string fails.

`println(Klaxon().toJsonString( BarImpl(1, FooImpl(1))))`

yields:

```Kotlin
Caused by: java.lang.NoSuchFieldException: x
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at com.beust.klaxon.Annotations$Companion.findJsonAnnotation(Annotations.kt:15)
	at com.beust.klaxon.DefaultConverter.toJson(DefaultConverter.kt:40)
	... 10 more
```

It appears as if Klaxon may have some cognitive dissonance on whether the delegated property "x" belongs in the body "BarImpl" or the contained "FooImpl" or in both.

The error can be  circumvented by declaring BarImpl like so:

```Kotlin
data class BarImpl(val y: Int, val foo: FooImpl): Foo by foo
{
	@Json(ignored = true)
	override val x = foo.x
}
```
Which yields:

```JSON
{"foo" : {"x" : 1}, "y" : 1}
```

with delegated properties being ignored in the output, which I presume is the preferred behavior over pulling them out of inner classes or showing them twice. Of course working around per-property this way defeats the point of delegation. :p

Thanks!

**Comment by cbeust** [comment]
Mmmh I just tried this exact same test:

```
interface Foo{ val x: Int }
data class FooImpl(override val x: Int): Foo
data class BarImpl(val y: Int, val foo: FooImpl): Foo by foo

@Test
class Bug {
    fun f() {
        println(Klaxon().toJsonString(BarImpl(1, FooImpl(1))))
    }
}
```
and it passes:

```
{"foo" : {"x" : 1}, "x" : 1, "y" : 1}
Disconnected from the target VM, address: '127.0.0.1:55411', transport: 'socket'

===============================================
Default Suite
Total tests run: 1, Failures: 0, Skips: 0
===============================================
```

Make sure you're using the latest version? (2.1.7) 

Feel free to reopen if you can reproduce.

**Comment by hughartk** [comment]
D'oh, thought I was up to date. Looks like I was running 2.1.0. Can't reproduce in 2.1.7. Thanks for looking into it!
