### ISSUE TITLE
Float instead of Double in constructor unsupported?

### ISSUE THREAD

**Issue by Archer6621** [cbeust/klaxon#124]
Hi,

I attempted to use Klaxon for parsing a JSON array containing objects that have floats in them. These objects correspond directly to a data class I have with those same fields of type Float. However, when trying to parse the array with Klaxon, it complains that no suitable constructor was found, even though it could find all the necessary fields and their corresponding values.

After some headaches I discovered that using doubles instead of floats in the constructor fixed the problem, but this is not really a desirable solution, since I'm bound to using floats everywhere in my program ( a LibGDX project), meaning I would have to do type conversions all over the place. It seems that Klaxon doesn't want to initialize objects that have floats in their constructor.

Is it correct that Klaxon doesn't support this? If so, will there be support for it sometime in the future? Thank you for reading!

**Comment by cbeust** [comment]
Yes, I'll add support for this shortly.

**Comment by Archer6621** [comment]
Thanks!

**Comment by cbeust** [comment]
Fixed in 2.1.14.
