### ISSUE TITLE
Can library work in kotlin/native?

### ISSUE THREAD

**Issue by nailgilaziev** [cbeust/klaxon#127]
Can I use this lib in common modules for kotlin/native? Or any plans to support it?

**Comment by cbeust** [comment]
I don't know :-)

You're welcome to try and report back :-)

**Comment by nbaklanov-issart** [comment]
I didn't managed to make it work in common module for multiplatform kotlin app. At least for this moment.

**Comment by shartte** [comment]
It uses classes that come from the JVM and as a result shouldn't work in Kotlin Native.
This would likely require a pretty significant rewrite to get rid of all of the java.* imports.

**Comment by anonym24** [comment]
is there any libraries for native?

**Comment by cbeust** [comment]
Not supported in native.
