### ISSUE TITLE
Cant convert SuperClass's fields to json? 

### ISSUE THREAD

**Issue by heiyeliuying** [cbeust/klaxon#128]
```
open class BaseRequest(var packageName:String = "",
                       var version:Int = 1,
                       var deviceID:String = "",
                       var userName: String="",
                       var userToken:String=""):Serializable
```
below is my subClass code : 
`open class UserRegisterRequest(userName: String ,var pwd:String): BaseRequest(userName = userName){}`

and when i  "Klaxon().toJsonString(this)" .the result is : 
` {"pwd" : "2A6A0C73442CD075CE39DBD2248CACAE"}`

**Comment by cbeust** [comment]
I am getting a different result:

```
        val a = UserRegisterRequest("foo", "password")
        println("OBJ: " + Klaxon().toJsonString(a))

OBJ: {"pwd" : "password", "deviceID" : "", "packageName" : "", "userName" : "foo", "userToken" : "", "version" : 1}
```

Are you using the latest Klaxon version?

Can you include the full code you're using?

**Comment by heiyeliuying** [comment]
Sorry . I does not use the last version. This problem is fixed in the lasted version. thanks a lot .

And do you have test this : 
convert this json to obj  UserRegisterRequest: 
```
 {"pwd" : "122345", "deviceID" : "dfdfdf", "packageName" : "com.klaxon.demo", "userName" : "foo", 
  "userToken" : "dfdf", "version" : 1}
```
The fields of the   BaseRequest is always the default value. 

  -----  with  compile 'com.beust:klaxon:2.1.13'

**Comment by cbeust** [comment]
This is working as expected. `UserRegisterRequest`'s constructor only has two parameters, and you'll notice that these two parameters are correctly initialized with the JSON values.
