### ISSUE TITLE
Some actual, up-to-date documentation?

### ISSUE THREAD

**Issue by Atulin** [cbeust/klaxon#131]
I've been trying to get Klaxon to work for the past hour, but no cigar. ``Parser()`` is deprecated, ``Klaxon()`` is an unresolved reference, installation instructions don't specify in which of fifty ``build.gradle`` files the lines have to be added, and Wiki promises... something while not delivering on the promise.

Is some actual, detailed documentation planned anytime soon? Or am I left to try and ask for help people who somehow obtained the arcane knowledge of how to use Klaxon?

**Comment by cbeust** [comment]
I'm surprised, all the snippets in the documentation should build and run. What specifically are you having difficulties with?

**Comment by Atulin** [comment]
Mostly with having not enough information to work with, but in this case with
![image](https://user-images.githubusercontent.com/11233299/38211433-bc8ab51e-36ba-11e8-9996-f1fb22574eb5.png)
appearing, even though
![image](https://user-images.githubusercontent.com/11233299/38211454-cd2bcec6-36ba-11e8-8d71-27240130077b.png)
Is present in ``app/build.gradle`` and the project cleaned and rebuilt.

Also, the ``Install`` section of the readme merely throws some lines of code at the reader, without as much as an indication of which file should they go to. One can assume they go to ``build.gradle``, but the projects have a tendency to have five of those at minimum.

**Comment by Atulin** [comment]
Turns out it was my bad. Out of 662182 ``different build.gradle`` files I picked the wrong one. Besides ``parse<>`` wanting a string instead of a class, everything's working just peachy.

**Comment by cbeust** [comment]
Closing, then. Feel free to join us on the #klaxon slack if you have further questions.
