### ISSUE TITLE
Converter example not working

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [cbeust/klaxon#135]
In the documentation of the Custom types converter, I get these errors.
- `object must be declared abstract or implement abstract member`
- `toJson overrides nothing`
![image](https://user-images.githubusercontent.com/5278928/39243035-3053dc4a-485a-11e8-96cf-208dc421dd34.png)
Seems as if the example does not implement the given interface correctly, for example, the Interface receives String, not a nullable String?

**Comment by cbeust** [comment]
Good catch, I forgot to update this snippet. `toJson()` accepts an `Any` in the latest update (breaking change, hence the major version bump).

**Comment by Karlheinzniebuhr** [comment]
may I ask a quick question? I need to convert a Boolean into an Int. There is a method for accessing Int (objInt) and String (objString) but not Bool. Do I have to implement it in the Converter class or what would be best practice?
![image](https://user-images.githubusercontent.com/5278928/39265438-4389aa66-4895-11e8-95a5-6a21575c65a8.png)

**Comment by Karlheinzniebuhr** [comment]
figured it out, just had to call obj?.get
Thanks!!
