### ISSUE TITLE
Slack link in README requires an `@jetbrains` email address to create an account

### ISSUE THREAD

**Issue by dvdsgl** [cbeust/klaxon#144]
Here is what I see when I try to join slack via the link in the README:

<img width="683" alt="image" src="https://user-images.githubusercontent.com/108197/39657257-1ae59ea8-4fbb-11e8-8124-93da22e57cac.png">

It says I can only create an account "if [I] have an @jetbrains.com email address".

**Comment by bshaffer** [comment]
+1 to this... would love to join slack channel but I don't have a JetBrains email.

**Comment by arjank** [comment]
We can to use https://slack.kotlinlang.org/ to request access.

**Comment by cbeust** [comment]
I believe anyone can join now.
