### ISSUE TITLE
Cannot serialize/deserialize non constructor variables

### ISSUE THREAD

**Issue by MinkiPan** [cbeust/klaxon#147]
> @Test
>     fun testParseRegistry() {
>         val result = Klaxon().parse<Registry>(registryString)
>         val vendors = result?.vendor!!
>         assertEquals("example", result.name)
>         assertEquals("cool", result.foo)
>         assertEquals("stuff", result.boo)
>         assertEquals("example", vendors[0].name)
>     }
> private class Registry(val name : String,
>                        val vendor : List<Vendor> = ArrayList()) {
>     var foo : String = ""
>     var boo : String = ""
> } 

throws java.lang.IllegalAccessException: Class com.beust.klaxon.JsonObjectConverter can not access a member of class at.willhaben.klaxon.Registry with modifiers "public final"

using version 3.0.2

**Comment by cbeust** [comment]
The following test passes with 3.0.3:

```
    private class Vendor {
        var vendorName : String = ""
    }

    @Language("json")
    private val someString = """{
        "name": "example",
        "foo": "cool",
        "boo": "stuff",
        "vendor": [
          { "vendorName": "example"}
        ]
    }"""

    @Test
    fun testParseRegistry() {
        val result = Klaxon().parse<Registry>(someString)
        val vendors = result?.vendor!!
        assertEquals("example", result!!.name)
        assertEquals("cool", result.foo)
        assertEquals("stuff", result.boo)
        assertEquals("example", vendors[0].vendorName)
    }
    private class Registry(val name : String,
            val vendor : List<Vendor> = ArrayList()) {
        var foo : String = ""
        var boo : String = ""
    }
```
