### ISSUE TITLE
Lexer throws RuntimeException

### ISSUE THREAD

**Issue by plannigan** [cbeust/klaxon#155]
When `Lexer` finds an unterminated string or unexpected character, it throws `RuntimeException`. This forces the calling code to catch `RuntimeException` when parsing, which will catch a wide range of exceptions that are unrelated to parsing JSON. The rest of the code base uses `KlaxonException` for parsing errors and this should as well.

**Comment by cbeust** [comment]
Good catch, feel free to send a PR.
