### ISSUE TITLE
nextString() will convert non-strings to string

### ISSUE THREAD

**Issue by plannigan** [cbeust/klaxon#156]
`JsonReader.nextString()` will return a string value even when the value is a number, boolean, or `null`. Since switching to only return a value for a string value would be a breaking change, adding a strict argument that defaults to false would allow for the user to decide if they want an exception when the value is not a string.

**Comment by plannigan** [comment]
I started working on a pull request and noticed that `nextDouble()` throws `IllegalStateException` when the value is not `Int` or `Double`.  However, the `nextInt()` and `nextBoolean()` throw `ClassCastException`. Should they all be changed so that the API is consistent (and documented)?

**Comment by cbeust** [comment]
Yup, PR welcome.

Don't worry about making a breaking change, I'll just publish it as a major version. I'd rather have a consistent API at the expense of breaking a few users.

**Comment by plannigan** [comment]
Ok. I can make the changes so that everything uses the same exception and `nextString()` will no longer convert other types to Strings.

Do you have an opinion on what exception should be used? To me, `IllegalStateException` and `ClassCastException` both give the impression that there was bug in how the Klaxon API was being used or some bug within Klaxon. However, the cause is most likely that the JSON being parsed had an unexpected value.

I'm leaning towards `IncorrectValueTypeException` as a subclass to `KlaxonException`. It would be more consistent with the rest of `JsonReader` which throws `KlaxonException` when the next token is not correct for the thing that was requested. In contrast `JsonObject` is all `ClassCastException`, but that's likely just because `as` gives it to you for free. It is easy enough to change once we've decided the "correct" exception to throw.

**Comment by cbeust** [comment]
How about introducing a `JsonParsingException` that would be a subclass of `KlaxonException`?

**Comment by plannigan** [comment]
Sure.
