### ISSUE TITLE
DefaultCoverter.toJson can't convert Array<String>

### ISSUE THREAD

**Issue by alfonso-eusebio** [cbeust/klaxon#162]
Hi,

When I convert an Array<String> to text I don't get the correct result:

Klaxon().toJsonString( arrayOf("test", "one") ) yields "[Ljava.lang.String;@7dccff43"

I'm not sure if basic Arrays are supposed to be supported, but the result is certainly unexpected and I can see that the DefaultConverter is not handling arrays in a way that would give the correct result.
Is this a bug or should I take a different approach? (Current workaround is to use .toList() on my arrays.)

Thanks!

**Comment by cbeust** [comment]
Definitely a bug. Should be trivial to fix if you feel inclined to send a PR (otherwise I'll take care of it).

**Comment by alfonso-eusebio** [comment]
Thanks Cedric!
I haven't cloned the repo and might take longer for me to get ready for a PR. However, I've tried the following  addition (through a custom converter for arrays) and it works, at least for arrays of strings:

            is Array<*> -> {
                val elements = value.filterNotNull().map { klaxon.toJsonString(it) }
                joinToString(elements, "[", "]")
            }
It's just a repeat of the Collection case.
Cheers
