### ISSUE TITLE
Does DSL support plain objects?

### ISSUE THREAD

**Issue by alfonso-eusebio** [cbeust/klaxon#167]
Hi Cedric,

I've been trying to serialise an object using the DSL but I can't find a way to do this:

```
val myObject = MyClass(1, "two", listOf())
val json = json {
    obj { "myobject" to myObject }
}
```

It throws Unrecognised type for MyClass.

Is there a simple way to recursively serialise objects within the DSL?
I think a possible approach would be to convert to JsonObject first, but I can't find how to do that either.

In the meantime I've been looking into a way to add this functionality to Render.renderValue() but it could be completely redundant if there's something already in place.

Thanks!

**Comment by alfonso-eusebio** [comment]
Hi,

Is this something that is actually missing from Klaxon or is it just me not being able to figure out how to do it?

I'm happy to try and create a potential solution, but don't want to duplicate something that might already be available somehow.

Cheers,
Alfonso

**Comment by cbeust** [comment]
Can you provide a compilable snippet? I tried to come up with one:

```
    class MyClass(i: Int, s: String, listOf: List<String>) {
    fun f() {
        val myObject = MyClass(1, "two", listOf())
        val json = json {
            obj("myobject" to myObject)
        }
    }
```

but this leads to

```
java.lang.IllegalArgumentException: Unrecognized type: com.beust.klaxon.MyClass@6d2a209c
```

which is expected.

**Comment by alfonso-eusebio** [comment]
When you say "which is expected", do you mean that this is intentionally not supported?
As you can see in my PR, it can be supported - and there is very similar code in the library that already implements object serialisation through introspection.

Perhaps I'm just trying to oversimplify things by attempting to use `json{obj() array()}` constructs for serialising any type of array/list or object/map. I can see that the library has the capability to handle all these combinations but it doesn't seem to use them in the case of the `json{}` DSL.

So, in the example that you used above, I would like to get the following output: `{"myobject": {"i": 1, "s": "two", "listOf":[]}}` (it's `[]` in this case, but ideally whatever happens to be in the `listOf`, recursively), without having to individually map each property to its value.

Maybe serialising through introspection is seen as a corner case, because in most cases objects are not ready to be exposed through JSON, and perhaps not ideal for other reasons (performance?).
At the moment I'm building "JSON-ready" (lists of) objects that then I try to serialise in the most concise manner with the DSL. Maybe I should take a different approach?

Thanks for your patience on this point, and for the great work on this library!

**Comment by cbeust** [comment]
Ok, I see what you're saying now!

First of all, note that your `data class` object above doesn't declare any of its parameters as `val`, so to Klaxon, it's an object with no properties. 

I'll continue this discussion on your PR.

**Comment by alfonso-eusebio** [comment]
I forgot to mention that after applying the PR there is a test (IllegalTypesTest.kt) that fails because it expects to get an exception that doesn't happen now.
I wasn't sure if I should remove the whole test file or just that one test funtion (which would leave the class empty), so I left it as it was.

Thanks for your patience!

**Comment by cbeust** [comment]
Yes, that test can be deleted, but there are a couple more test failures, please see my comment on the PR.

**Comment by alfonso-eusebio** [comment]
I've just rebased to your latest master and run the tests (under klaxon/src/test/kotlin) and all were fine:

```
===============================================
Default Suite
Total tests run: 159, Failures: 0, Skips: 0
===============================================
```

Please let me know if there is anything that's still different for you or that'd you'd like me to check.

**Comment by cbeust** [comment]
No, that's good, I fixed all the tests.
