### ISSUE TITLE
Type mismatch error when parsing JSON with an Integer into a String

### ISSUE THREAD

**Issue by voddan** [cbeust/klaxon#172]
I have  a problem when a property must be a string by semantics, but the JSON passes it as a raw integer. 

For example I have a class `Person` with an `id` which is a random string of any length:

    data class Person(val id: String)

Then I am trying to parse a person out of a JSON that comes from a 3rd-party service: 

    {
        "id" : 123456
    }

In this situation Klaxon throws a "type mismatch" exception because it can't put integer `123456` into a string property `id`. 

My current workaround is to change the property to be `Int`. This works, but it is problematic because the id may be very long, so I would need a `BigInteger` for it; also the API may change to return the id as a string with non-digit characters, which would break my code.

Q1: can you suggest a better workaround?
Q2: can we force any simple value to fit into a string property?

P.S. The library is absolutely gorges! I was able to parse an unfamiliar JSON API in a matter of minutes. Thank you!

**Comment by cbeust** [comment]
Why not write a field converter that will take that `Int` or `BigInteger` and convert it to a `String`?

**Comment by voddan** [comment]
Does that mean I would have to mark every such property with an annotation?

**Comment by erikchris2011** [comment]
We are trying to write a simple bit of tooling (similar to JQ) that simply dumps a JSON value given a key; this means we don't know (or care) whether it is an int or string. It would be useful to have a get-string method that always converted the value to a string (.toString()).

**Comment by cbeust** [comment]
@erikchris2011 Why not simply call `.toString()` on that value, just like you suggested yourself?

**Comment by erikchris2011** [comment]
It looks like the code in the obj.string() function does a cast to JsonObject:

```
 Exception in thread "main" java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
        at com.beust.klaxon.JsonObject.string(JsonObject.kt:74)
```

Maybe we're missing something, as we are brand new to Kotlin; here is the relevant code where we tried this:

```
 fun getStringValue(key: String) : String? {
        return getValue(key,
          {obj, fieldName ->
              obj.string(fieldName).toString() } )
    }
```
 
thanks Cedric!

**Comment by erikchris2011** [comment]
I think we're missing something about how to get the value as a generic thing... we are basically traversing a dot-separated "key" (e.g.  Alpha.Beta.ElementName), assuming everything but the last layer is a JsonObject:
```
fun getValue(key: String,
             convert: (obj: JsonObject, fieldName: String) -> String?)
    : String? {
    val fieldNames: List<String> = key.split('.')

    var obj: JsonObject = jsonParsed
    for (objFieldName in fieldNames.dropLast(1))
        obj = obj.obj(objFieldName) as JsonObject
    val fieldName: String = fieldNames.last()
    return convert(obj, fieldName)
}
```
Looking at JsonObject, it seems we have to know the type before getting the value. We tried using the obj() function, but that appeared to have similar casting problems with JsonObject.

**Comment by erikchris2011** [comment]
aha. The docs don't match the code, but digging through the code got us the answer we sought. Basically once we understood that the JsonObject used public implementation inheritance, we knew we could just directly access the property ("fieldName") by indexing the JsonObject directly. Thanks for the responses.
