### ISSUE TITLE
KlaxonJson doesn't support converting Short type

### ISSUE THREAD

**Issue by JLLeitschuh** [cbeust/klaxon#176]
Passing a `Short` value to be converted throws an `IllegalArgumentException` for the conversion.

https://github.com/cbeust/klaxon/blob/29c28693de15b6453bce6b7926ccc75a03c021fa/src/main/kotlin/com/beust/klaxon/KlaxonJson.kt#L21-L34

**Comment by jolkdarr** [comment]
Byte should be converted to Int as well.
