### ISSUE TITLE
Nesting custom and standard converters?

### ISSUE THREAD

**Issue by noncom** [cbeust/klaxon#179]
Consider this piece of code:

```
import org.apache.commons.math3.geometry.euclidean.threed.Vector3D

interface I {
    val v: Vector3D
}

class A(override v: Vector3D) : I {
    val name = "a"
}

class B(override v: Vector3D) : I {
    val name = "b"
}

class C(val i: I) {}
```

Serializing and deserializing the Apache Math `Vector3D` class works fine, no problem there.

Transforming an instance of `C` into a string works fine.

Transforming the string back into `C` gives a problem. That's understanable, and the only solution is to provide a converter that, looking at the value of `name`, will resolve the ambiguity and let Klaxon decide if what it is seeing is either an instance of `A` or `B`. The problem is: at that point I will have to write a converter for `Vector3D` too because there is no way to return the job to the standard converter from within `fromJson` of the custom one.

Ideally, after I have manually resolved the ambiguity with types, I'd be very glad to just go on with the standard converter because it does fine job for most of the simple classes. But currently, as I see it, I have to implement the whole swarm of converters for all the classes that happen to need deserialization from within the deserialization of the custom one.

The problem is that when I know that the field `v` stores a `Vector3D` object, I would like to give the job of serializing and deserializing it to the standard converter. Currently I do not know how to invoke the standard converter from within the custom one, it's private in `Klaxon`.

**Comment by cbeust** [comment]
`Klaxon#findConverterFromClass` is `public` in the `Klaxon` class, couldn't use that?

**Comment by noncom** [comment]
@cbeust that would most probably work, but there is no easy way to access the current `Klaxon` object from a `Converter`. I think that a custom converter could be instantiated with a `Klaxon` passed to its constructor, but that would make it impossible for the `Converter` to be an `object` and would necessiate unnecessary instantiation.

Likewise, instantiating a new `Klaxon` object from within the converters methods would also require first creating it and then configuring it with the stack of available converters.

That's the two scenarios of usage that I can think of now.. both seem to require much unnecessary allocations. Maybe I am missing something. What do you think?

**Comment by cbeust** [comment]
For now, you can create the `Klaxon` object and then pass it manually to your converter, can't you?

**Comment by cbeust** [comment]
Going to close this for now, let me know if you have a proposal for a better architecture between converter and `Klaxon` objects. I don't mind making breaking changes if they are improvements.
