### ISSUE TITLE
Where can I get 0.20 version?

### ISSUE THREAD

**Issue by cevek** [cbeust/klaxon#18]
`Could not find com.beust:klaxon:0.20.`
I found only 0.19 version in https://jcenter.bintray.com/com/beust/klaxon/

**Comment by cbeust** [comment]
0.20 is not released yet, do you need it?

**Comment by cevek** [comment]
Just play with kotlin. Your examples is not compatible with 0.19 version

**Comment by cbeust** [comment]
Really? Which ones?

-- 
Cédric

**Comment by cevek** [comment]
```
val logic = json {
        array(arrayListOf(1,2,3).map {
            obj(it.toString(), it)
        })
    }
```
`Error:(26, 17) Kotlin: Type mismatch: inferred type is kotlin.String but kotlin.Pair<kotlin.String, *> was expected`

**Comment by fboldog** [comment]
just write in this style:
```kotlin
        val logic = json {
            array(listOf(1,2,3).map {
                obj(it.toString() to it)
            })
        }
```

, but apart from this @cbeust can you publish 0.20 into jcenter? (it's contains latest (fixes)[https://github.com/cbeust/klaxon/commit/fb68b049409c9d47fc67e5ee6053464b113b32e9] for kotlin beta 2423)

**Comment by cbeust** [comment]
Yes, I'll publish 0.20 in the next few days.

-- 
Cédric

**Comment by fboldog** [comment]
:+1:

**Comment by cbeust** [comment]
0.20 is now on JCenter.
