### ISSUE TITLE
Performance dramatically slow

### ISSUE THREAD

**Issue by darkwood-studios** [cbeust/klaxon#181]
Hi there, 

I try to use the Klaxon parser together with android room.

So I have this example model:

```
@Entity
data class User(
        @PrimaryKey
        @Json(name = "user_id")
        var userID: String,

        @Json(name = "salutation")
        var salutation: String? = null,

        @Json(name = "company")
        var company: String? = null,

        @Json(name = "firstname")
        var firstName: String? = null,

        @Json(name = "lastname")
        var lastName: String? = null,

        @Json(name = "zip")
        var zip: String? = null
)
```

And want to parse it from this json string:
`{"firstname" : "George", "lastname" : "Clooney", "salutation" : "Herr", "user_id" : "530930", "zip" : "80335"}`

And this is the code which should do all the magic:

```
fun getUser(): User {
        val userJson = pref!!.getString(KEY_USER, "") // the preferences stores the json string from above
        return Klaxon().parse<User>(userJson)!! // this method takes 8 seconds in debug mode!
    }
```

According to the Android Studio Profiler the slow method is "findJsonPaths" called in Klaxon.kt 

I do have the same performance problems at any part where I'm using the klaxon parser. Any ideas for issue?

Thanks for help.

**Comment by cbeust** [comment]
Can you share a few numbers? What does "dramatically slow" mean?

**Comment by darkwood-studios** [comment]
please see the comment in getUser function

> this method takes 8 seconds in debug mode!

**Comment by darkwood-studios** [comment]
I tried it with moshi parser and got a mush better result with this code

```
fun getUser(): User {
        val userJson = pref!!.getString(KEY_USER, "") // the preferences stores the json string from above
        val moshi = Moshi.Builder().build()
        val userAdapter = moshi.adapter(User::class.java)
        return userAdapter.fromJsonValue(userJson)!! // this method takes only some milli seconds!
}
```
Any idea why Klaxon is so much slower? Maybe I missed some configuration etc.

**Comment by cbeust** [comment]
No, I think it's a genuine issue. Will take a look.

**Comment by darkwood-studios** [comment]
Here are some further speed comparisons. I did the same parsing operation, ten times for each parser version, and calculated the average time.

Klaxon 3.0.1 ~ 00:49 
Klaxon 2.0.11 ~ 00:21
Moshi 1.6.0 ~ 00:16

Maybe this could help to find the problem.

**Comment by darkwood-studios** [comment]
@cbeust  Any news on this?

**Comment by cbeust** [comment]
Have you tried with the Jackson parser?

**Comment by darkwood-studios** [comment]
No, only with Moshi so far.

**Comment by cbeust** [comment]
Can you try with the Jakson parser? Details [here](https://github.com/cbeust/klaxon#parsers).
