### ISSUE TITLE
Can Klaxon unify parsing JsonObject and JsonArray?

### ISSUE THREAD

**Issue by jeiea** [cbeust/klaxon#182]
I made a class for [ktor-client](https://ktor.io/clients/http-client.html#specifying-a-body-for-requests) json content negotiation feature.
```
class KlaxonSerializer(block: Klaxon.() -> Unit = {}) : JsonSerializer {

  private val backend: Klaxon = Klaxon().apply(block)

  override fun write(data: Any): OutgoingContent =
    TextContent(backend.toJsonString(data), ContentType.Application.Json)

  override suspend fun read(type: TypeInfo, response: HttpResponse): Any {
    val text: String = response.readText()
    val json = backend.parser(type.type).parse(StringBuilder(text)) as JsonObject
    return backend.fromJsonObject(json, type.javaClass, type.type)
  }
}
```
But it can parse only one of `JsonObject` or `JsonArray`. Can it be better?

**Comment by cbeust** [comment]
You need to know ahead of time whether you are getting one or the other. How do you suggest to improve this?

**Comment by jeiea** [comment]
How about to test whether a destination type is implementing something like `Iterable<T>`?

I know there is `GsonSerializer` that already achieve this, but I don't know well how Gson handle this.
