### ISSUE TITLE
UTF-8 streams will be butchered by lexer

### ISSUE THREAD

**Issue by ssuukk** [cbeust/klaxon#19]
Hi,

Your lexer assumes that the input stream is URL encoded (with /uxxxx and so on). I'm not really a JSON expert, but I haven't ever seen such JSON! All streams I've seen were just UTF-8 encoded and that causes the output to be hopelessly messed (due to char-byte-char encoding) with any non-ansi character. I think I will fix it just by changing your code to operate on chars instead of bytes. But you might look into this issue.

**Comment by fboldog** [comment]
Could you provide a problematic example? I saw what is the problem, but a real world example, always better. ;)

**Comment by ssuukk** [comment]
Surely, but not earlier than Monday evening. If I can find any API that doesn't require my private key... BTW - thanks for klaxon, it helps keep my code neat ;)

**Comment by WinterGrascph** [comment]
The issue still persists. "ú" and "\u00FA" should produce the same output when parsed. The former get mangled. (Great API btw:)

**Comment by cbeust** [comment]
I would really like to see a concrete example where Klaxon fails, then I can add it as a regression test and fix it.

Thanks!

**Comment by VladRassokhin** [comment]
Problem lies in `Lexer#nextChar` as it assumes that all chars are single-byte, which is false for example for `é` (part of your name, Cédric) as it's two bytes `C3` and `A9`. 
Simple test to reproduce is to add next method to `TestRFC7159` class.
```kotlin
    fun unicodeUnescaped() {
        jsonEquals("{\"a\":\"ú\"}", "{\"a\":\"ú\"}")
    }
```
