### ISSUE TITLE
Using different patterns for naming in json structure and Kotlin object, how?

### ISSUE THREAD

**Issue by arjank** [cbeust/klaxon#196]
My json structure has field names like `first_name` and `last_name`, but my Kotlin class has properties like `firstName` and `lastName`. Of course I could add `@Json()` annotations to each Kotlin property, but that is cumbersome and error prone. It's not hard to convert the field names, but I'm still trying to understand where to start with Klaxon (I guess it should be possible), and what I would need to glue the pieces together. Could you give some clues?

**Comment by cbeust** [comment]
Well, you gave the answer yourself, use `@Json` annotations with the corrected names.

Maybe you are suggesting adding support for some kind of name converter that would automate that?

**Comment by cbeust** [comment]
I was more thinking of introducing a new interceptor, e.g.

```
interface FieldRenamer {
  fun renameField(fieldName: String): String
}
```

which gets called for each field so that the user gets a chance of renaming that field before it gets seen by Klaxon.

What do you think?

**Comment by arjank** [comment]
Looks good 👍 I'm not yet fully sure about the internal workings of Klaxon, but if this works both ways (to and from json) it should be okay. Otherwise you might need two functions in the interface.

**Comment by cbeust** [comment]
Oh yes, of course, good point.
