### ISSUE TITLE
Cannot construct instance with float field if document does not contain decimal point

### ISSUE THREAD

**Issue by keturn** [cbeust/klaxon#197]
```kotlin

data class Thinger(
    val width: Float?=null
)

class ThingerTest {
    @Test
    fun testThingerFromJSON() {
        val input = """{"width": 2}"""
        val thinger = Klaxon().parse<Thinger>(StringReader(input))!!

        assertEquals(thinger.width, 2f)
    }
}
```

Fails with

> com.beust.klaxon.KlaxonException: Couldn't find a suitable constructor for class Thinger to initialize with {width=2}: java.lang.IllegalArgumentException argument type mismatch

**Comment by cbeust** [comment]
Doesn't JSON mandate that you write the float `2.0` here?

**Comment by keturn** [comment]
In practice, this is what happens in both Chrome and Firefox:

```
> JSON.stringify({width: 2})
"{\"width\":2}"
> JSON.stringify({width: 2.0})
"{\"width\":2}"
```

and as far as the spec goes, JSON (as well as ECMAScript) only has a single Number type, so no, they don't (and often *can't*) distinguish between `2` and `2.0`.

(While recent ECMAScript implementations certainly have integer representations inside them somewhere, but that's beside the point here.)
