### ISSUE TITLE
Splicing/Templating

### ISSUE THREAD

**Issue by codeslubber** [cbeust/klaxon#20]
This is really more of a suggestion.

So I am using Klaxon to generate digital passes for Wallets. The format of the pass has a bunch of boilerplate in it. Probably the best way to do this would be to have the basic pass template in a file, then replace some of the fields. I was thinking it might be nice to have a way to basically say 'parse this file into a new structure, then graft these new nodes to it, and replace these couple fields.'

Seems like that could be done with what is here. Just wondering if there's any interest in making that part of the lib.

**Comment by cbeust** [comment]
Can you give an example of what this would look like?

**Comment by codeslubber** [comment]
Sure. So here is the example Apple Wallet pass:

{code}
{
  "formatVersion" : 1,
  "passTypeIdentifier" : "pass.com.apple.devpubs.example",
  "serialNumber" : "E5982H-I2",
  "teamIdentifier" : "A93A5CM278",
  "webServiceURL" : "https://example.com/passes/",
  "authenticationToken" : "vxwxd7J8AlNNFPS8k0a0FfUFtq0ewzFdc",
  "barcode" : {
    "message" : "123456789",
    "format" : "PKBarcodeFormatPDF417",
    "messageEncoding" : "iso-8859-1"
  },
  "locations" : [
    {
      "longitude" : -122.3748889,
      "latitude" : 37.6189722
    },
    {
      "longitude" : -122.03118,
      "latitude" : 37.33182
    }
  ],
  "organizationName" : "Paw Planet",
  "description" : "Paw Planet Coupon",
  "logoText" : "Paw Planet",
  "foregroundColor" : "rgb(255, 255, 255)",
  "backgroundColor" : "rgb(206, 140, 53)",
  "coupon" : {
    "primaryFields" : [
      {
        "key" : "offer",
        "label" : "Any premium dog food",
        "value" : "20% off"
      }
    ],
    "auxiliaryFields" : [
      {
        "key" : "expires",
        "label" : "EXPIRES",
        "value" : "2013-04-24T10:00-05:00",
        "isRelative" : true,
        "dateStyle" : "PKDateStyleShort"
      }
    ]
  }
}
{code}

Suppose all I want to do is plugin my own organization id, I would want to do something like:

{code}
val pass = Parser().from(template).replace({ obj( "organizationId" to 12345678 ) })
{code}

and the result would be that that value was spliced in to the json which was copied from the parse operation.

**Comment by cbeust** [comment]
Sounds pretty useful but I'm not sure this belongs in a JSON parsing library. Better let the developer pick their own templating approach, for that (e.g. Mustache).

**Comment by codeslubber** [comment]
The problem with treating it as a template is then it seems to undo one of the best parts of JSON: so we parse and stringify and then parse again to replace a single value?

I have heard your ruling though. :)

**Comment by codeslubber** [comment]
Not that it means that much, doing this is pretty trivial in (SwiftyJSON)[https://github.com/SwiftyJSON/SwiftyJSON].
