### ISSUE TITLE
Return `null` from `Converter`

### ISSUE THREAD

**Issue by FWDekker** [cbeust/klaxon#206]
Currently, the `Converter`'s `fromJson` method must return `Any`, which precludes returning `null` values. However, I think there are legitimate situations in which `fromJson` should return `null`, in particular when the converter is used as a field converter.

For example, consider the following JSON:

```json
[
  {
    "name": "Felix",
    "phone": "Nokia"
  },
  {
    "name": "Jake",
    "phone": ""
  }
]
```

and the following classes:

```kotlin
data class Person(
    val name: String,
    @PhoneAnnotation
    val phone: Phone?
)

data class Phone(val type: String)
```

In this case, it is not possible to use a field converter for the `phone` field. A workaround would be to use a converter for the entire `Person` class, but if `Person` is a class with, say, 20 fields, this would result in a lot of unnecessary code.

Am I perhaps overseeing another solution to this problem?

**Comment by cbeust** [comment]
Mmmh... yes, maybe.

My working assumption was that if your converter returned `true` in `canConvert()`, then it is expected to be able to convert that value, `fromJson()` should always return a nonnull value.

**Comment by FWDekker** [comment]
That's not an unreasonable assumption. Because I'm using it as a field converter, though, I can't invoke `canConvert()` myself. What happens if it returns `false`? Will it throw an exception or does it just return `null`?

**Comment by FWDekker** [comment]
I've changed the `canConvert` function in my program to always return `false`, and nothing changes—it still happily converts the value. Is this intended?

To return to my issue, is there an idiomatic way of returning `null` from a converter, or is that just not what they're meant for?

**Comment by cbeust** [comment]
I don't follow, if `canConvert()` returns `false`, then your converter should never be invoked.

Feel free to come to Slack if you want to go into more details.

**Comment by FWDekker** [comment]
I need an `@JetBrains.com` email address to enter the Slack, which I don't have. I tried signing up [here](https://surveys.jetbrains.com/s3/kotlin-slack-sign-up), but I didn't receive an invite yet.

About my usage of the converter, I used the example from the README's "Field conversion overriding" section. In addition to the code I gave in the issue description, I have the following:

```kotlin
@Target(AnnotationTarget.FIELD)
annotation class PhoneAnnotation

class PhoneConverter : Converter {
    override fun canConvert(cls: Class<*>) = cls == Phone::class.java

    override fun fromJson(jv: JsonValue) = Phone(jv.string!!)

    override fun toJson(value: Any) = "\"${(value as Phone).type}\""
}


fun main(args: Array<String>) {
    val persons = Klaxon()
        .fieldConverter(PhoneAnnotation::class, PhoneConverter())
        .parseArray<Person>(File("persons.json").inputStream())
}
```

If I change the `canConvert` function to always return false, nothing changes when I execute the `main` function.

My goal is to set the `phone` field of the `Person` object to `null` if the JSON's `phone` property is an empty string, but because the `fromJson` function cannot return `null` it sets the `phone` field to `Phone("")` instead.

**Comment by cbeust** [comment]
I see. I guess it would make sense for `toJson()` to be nullable then, I'll make the change.
