### ISSUE TITLE
Ignore properties when deserializing to an object?

### ISSUE THREAD

**Issue by bfinleyui** [cbeust/klaxon#209]
I've got a json input that I only need a few of the fields mapped to an object, and don't care about the rest.

Unless i'm super dumb (which is always a possibility) it seems like the examples in the docs are for ignoring fields on serialization, rather than when mapping into an object.

Back in the boring java world, using Jackson, it'd be @JsonIgnoreProperties(ignoreUnknown = true), but hoping there's a Klaxon equivalent? 

Thanks

**Comment by cbeust** [comment]
Fields found in JSON that don't have a Kotlin equivalent are simply ignored.

Or are you trying to do something else? Can you paste some code?
