### ISSUE TITLE
Object binding doesn't handle nulls.

### ISSUE THREAD

**Issue by JakeCB** [cbeust/klaxon#210]
For json:
{
"some": "test",
"none": null
}

and data class:
data class DClass(val some: String, val none: String?)

Exception:
com.beust.klaxon.KlaxonException: Unable to instantiate DClass with parameters [some: test]

It looks like null is being filtered. Is String? not the way to model a field that can either be a String or null in json?

Tried versions 3.0.1, 3.0.8, and 4.0.1

**Comment by JakeCB** [comment]
After some more testing I can get around this by making the String? default to null. If that's the intended usage go ahead and close this. I note on the readme about nullable might be useful though.

**Comment by cbeust** [comment]
No, I don't believe this is the correct workaround, your initial example should work without requiring the default value.

It's a bug, I'll look into it.

**Comment by sith** [comment]
What was the version when it was fixed? I use 5.0.5 and can reproduce the issue
