### ISSUE TITLE
PropertyStrategy is not found in the library

### ISSUE THREAD

**Issue by tkshnwesper** [cbeust/klaxon#211]
Hello,

I was looking through your documentation on how I could dynamically ignore certain fields, and stumbled upon `PropertyStrategy`, but it appears that it doesn't exist in the library.

**Comment by cbeust** [comment]
I see it here:

https://github.com/cbeust/klaxon/blob/master/klaxon/src/main/kotlin/com/beust/klaxon/PropertyStrategy.kt

**Comment by tkshnwesper** [comment]
Are you sure it is there in the `3.0.1` release? Because it is definitely not there when I try to import it.
