### ISSUE TITLE
Alternate constructor not considered

### ISSUE THREAD

**Issue by arvearve** [cbeust/klaxon#212]
I would expect the following to work, but got an exception. Doesn't seem the alternate constructor is being considered.

Test case:
```kotlin
data class Thing(val doodads: List<String>) {
    constructor(doodads: Map<String, Boolean>): this(doodads.keys.toList())
}

val json = """ {
    "doodads": {
        "a": true,
        "b": true,
    }
}""".trimIndent()

Klaxon().parse<Thing>(json) 
/*  com.beust.klaxon.KlaxonException: 
    Couldn't find a suitable constructor for class Thing to initialize with {controllers=}: 
    java.lang.IllegalArgumentException argument type mismatch */

```

**Comment by cbeust** [comment]
This can't work since Klaxon will never see the `doodads` parameter in the secondary constructor, since it's not a `val`. Therefore, it only sees `val doodads: List<String>`, which cannot be converted from a `JsonObject`.
