### ISSUE TITLE
Deserialize enum class 

### ISSUE THREAD

**Issue by bkchr** [cbeust/klaxon#230]
Hi,
I want to deserialize the following json `"Threshold"` as enum `Setting`.
The enum is defined as:
```
enum class Setting {
        MonitoringTime,
        Threshold,
}
```

However, I just get the following exception:
`java.lang.ClassCastException: java.lang.String cannot be cast to com.beust.klaxon.JsonObject`

As far as I know, `"Threshold"` is valid json.

**Comment by cbeust** [comment]
Can you include the JSON?

**Comment by cbeust** [comment]
Actually I took a guess, and it seems to work with an `enum` fine:

https://github.com/cbeust/klaxon/blob/master/klaxon/src/test/kotlin/com/beust/klaxon/Issue230Test.kt

**Comment by bkchr** [comment]
The json is just `"Threshold"`, nothing more. And giving that to Klaxon, does not work.

**Comment by cbeust** [comment]
Please provide a fully contained test that fails.
