### ISSUE TITLE
Deserialize HashMap

### ISSUE THREAD

**Issue by bkchr** [cbeust/klaxon#231]
I want to deserialize the following json, as a `HashMap<String, SettingValue>`:
```
{
    "Threshold": { "type": "Threshold", "value":0.4 },
    "MonitoringTime" : {"type": "MonitoringTime", "value":4}
}
```

`SettingValue` is defined as:
```
    @TypeFor(field = "type", adapter = SettingValueAdapter::class)
    open class SettingValue(val type: String)
    data class MonitoringTime(val value: Int) : SettingValue("MonitoringTime")
    data class Threshold(val value: Double) : SettingValue("Threshold")

    class SettingValueAdapter : TypeAdapter<SettingValue> {
        override fun classFor(type: Any): KClass<out SettingValue> = when (type as String) {
            "MonitoringTime" -> MonitoringTime::class
            "Threshold" -> Threshold::class
            else -> throw IllegalArgumentException("Unknown type: $type")
        }
    }
```

As a result, I just get a `HashMap` that is empty.
I use `Klaxon().parse<HashMap<String, SettingValue>>(data_str)` to deserialize it.

Ideally, `String` should also be replaced by `Setting`, as defined in https://github.com/cbeust/klaxon/issues/230

**Comment by cbeust** [comment]
I can't reproduce the problem, I created a test for this:

https://github.com/cbeust/klaxon/blob/master/klaxon/src/test/kotlin/com/beust/klaxon/Issue231Test.kt

See if you can modify it and make it fail?

**Comment by bkchr** [comment]
I want to decode a `HashMap`, not just `Data` with two parameters. The Json could contain more lines.

**Comment by cbeust** [comment]
I modified the test to use a map, and I get the expected result:

![image](https://user-images.githubusercontent.com/92322/50728124-f1ab6500-10d9-11e9-9401-a5510e4460b5.png)

Please provide a fully contained test that fails.
