### ISSUE TITLE
Parsing json with null value to a data class causes KlaxonException instead of using default value

### ISSUE THREAD

**Issue by smckend** [cbeust/klaxon#232]
This scenario worked fine in Klaxon 4.0.1.

After upgrading to version 5.0.4, when trying to parse json into a data class there was an issue where a null valued key in a json would no longer resort to the default value of a given data class but instead throw a KlaxonException saying 

" Unable to instantiate <class name> with parameters <pairs stripped from json>"

E.g { "somekey": null }

data class someClass(val someKey: String = "")

Klaxon().parse<AuthUserData>(jsonString) // KlaxonException

Is this done by design? Would anyone recommend another approach to this problem?

Thanks in advance,
Sam

**Comment by cbeust** [comment]
The previous behavior was incorrect. If there is a `null` in the JSON document, then that parameter should be present in the Kotlin class, set to `null`, and not to its default value.

Klaxon will only use default values in Kotlin if the key is missing from the JSON.

Does this make sense?

**Comment by smckend** [comment]
It makes sense, just wanted to double check which behaviour would be correct going forward before we updated our own logic. Thanks for the prompt reply
