### ISSUE TITLE
5.0.4 breaks DSL serialisation of JsonArray

### ISSUE THREAD

**Issue by alfonso-eusebio** [cbeust/klaxon#237]
Hi Cedric,

I've updated to 5.0.4 and have noticed that my previous code doesn't work when I have a JsonObject that includes a mapping to a JsonArray.

```
val test = json {
    obj ( "key" to someJsonArray )
}
```

Trying to serialise this with `Klaxon().toJsonString(test)` would return a json string that in the form:

`{"key": "the entire content of someJsonArray as a string"}`

I believe this is due to a change introduced in one of your latest commits: 2087696a58b593692be8ba7bc53960e0411352b5

In DefaultConverter.kt this commit replaces the previous recursive parsing of values with klaxon.toJsonString() with a conversion to String.

Is this intentional and there is another way to properly create the `test` json object so that it can be serialised?

Thanks!

**Comment by cbeust** [comment]
Seems to work for me:

```
    fun issue237() {
        val test = json {
            obj ( "key" to """[1, 2, 3]""" )
        }
        println(Klaxon().toJsonString(test))
    }
```

Output:

```
Connected to the target VM, address: '127.0.0.1:53237', transport: 'socket'
{"key": "[1, 2, 3]"}

===============================================
Default Suite
Total tests run: 1, Failures: 0, Skips: 0
===============================================
```

**Comment by alfonso-eusebio** [comment]
Thanks for looking into this.

I think there is some confusion. I meant literally a Klaxon JsonArray object, not a literal string that the represent a JSON array.

**Comment by cbeust** [comment]
Ah ok. I modified the test:

```
    fun issue237() {
        val test = """
            { "key": [1,2,3] }
        """
        println(Klaxon().toJsonString(test))
```

and still get the expected result (I think):

```
"\n            { \"key\": [1,2,3] }\n        "
```

Am I missing something?

**Comment by alfonso-eusebio** [comment]
Sorry Cedric, I think I should have been more specific from the beginning. This is the type of code that now breaks with 5.0.4:
```
val json = json {
    obj (
        "items" to array (items.toList())
    )
}
```
In this example, I use `array()` to return a `JsonArray` object, but I could have used a `JsonArray` object built some other way.
This was working fine up until 5.0.3, but in your commit 2087696a58b593692be8ba7bc53960e0411352b5 there is a change in DefaultConverter.kt where the handling of the values inside a `Map` was changed from using `klaxon.toJsonString()` to doing an implicit toString() conversion with `""""${entry.value}""""`, which produce completely different outputs.

Using `klaxon.toJsonString(entry.value as Any)` for the non-null case again would solve the problem.

I hope this clarifies the issue.

**Comment by cbeust** [comment]
Good catch! I'll fix it unless you send me a PR first (with a test if possible).

Thanks!

**Comment by alfonso-eusebio** [comment]
Thanks for merging the PR. Looking forward to the next release!
