### ISSUE TITLE
Subscript json element

### ISSUE THREAD

**Issue by siideffect** [cbeust/klaxon#244]
Hi, im using this library to parse a Json with kotlin:
```
            override fun onResponse(call: Call, response: Response) {
                println("-------- ---------")
                val result = response.body()?.string()
                println("The response is: $result")
                
                if (result != null){
                    val json = Klaxon().parse<List<Person>>(result)
                    println("FOUND ${json?.count()} records ")
                }
            }
        })
```

The json however, comes in this form

`{"results":[{"name":{"title":"mr","first":"lorenzo","last":"martin"},"email":"lorenzo.martin@example.com","phone":"922-246-718","cell":"616-037-433","picture":{"large":"https://randomuser.me/api/portraits/men/74.jpg","medium":"https://randomuser.me/api/portraits/med/men/74.jpg","thumbnail":"https://randomuser.me/api/portraits/thumb/men/74.jpg"}}, ... }]}`

and not in the form 
{[ ... ]}

Is it possible to subscript this? Im sorry but im pretty new to android development

**Comment by cbeust** [comment]
Create a wrapper class `class Results(val results: List<Person>)` and `parse<Results>(json)`.
