### ISSUE TITLE
Improve performance of  parser when consuming each character during tokenization

### ISSUE THREAD

**Issue by hooddanielc** [cbeust/klaxon#245]
I noticed that a switch statement is not used [here in Lexer.kt](https://github.com/cbeust/klaxon/blob/master/klaxon/src/main/kotlin/com/beust/klaxon/Lexer.kt#L88). Doesn't compiler optimize better when this is a `when` statement instead of a bunch of `if/else` statements?

**Comment by cbeust** [comment]
Unclear it would yield any improvement, but I know better than guessing. Can you try both ways and run a profiler to find out?

**Comment by cbeust** [comment]
Closing this for now as not an issue, but happy to reopen if the profiler tells you there's a genuine performance issue with the current implementation.
