### ISSUE TITLE
Null field is not serialized, causing deserialization to fail

### ISSUE THREAD

**Issue by mverleg** [cbeust/klaxon#253]
I have an object with a nullable field. When serializing it, this field is skipped. When deserializing, it fails, probably because the field is missing.

This short test reproduces the problem for me (on v5.0.2):

    import com.beust.klaxon.Klaxon
    import org.junit.jupiter.api.Test
    
    data class MyObj(val myAttr: Int?) {}
    
    internal class KlaxonTest {
        @Test
        fun testEncDec() {
            val obj = MyObj(null)
            val json = Klaxon().toJsonString(obj)
            println(json)  // output: {}
            Klaxon().parse<MyObj>(json)
            // fails: Unable to instantiate MyObj with parameters []
        }
    }

If I provide a number instead of null, the test passes. The type does not seem to matter, nor does being a data class.

**Comment by mverleg** [comment]
I think it's going wrong [over here](https://github.com/cbeust/klaxon/blob/1bee993d98f25998205a7c7447290cb3a4be4695/klaxon/src/main/kotlin/com/beust/klaxon/DefaultConverter.kt#L71). I'll see if I can make a PR

This is under the assumption that the problem here is the encoding (where nulls are skipped). One could argue that it's okay to skip nulls and that decoding should work.

**Comment by mverleg** [comment]
I'll close this since it has been merged. If someone feels decoding should work with missing fields, perhaps best create a new issue.

**Comment by mverleg** [comment]
@cbeust Is any new maven release planned? It's kind of broken for me if nulls are not supported.

**Comment by alex88** [comment]
Just as an additional example https://github.com/google/gson/blob/master/UserGuide.md#null-object-support gson explains better the difference and how they handle having nulls omitted from the output but you can opt-in to have them

**Comment by Firionus** [comment]
@alex88 I added the ability to make null properties absent in the serialized JSON. See Pull Request #326 that is already merged into master. If you find the time to check it out, I'd be happy to know about any issues you encounter.

**Comment by zaleslaw** [comment]
Great feature, thanks @Firionus . Dear @cbeust, do we have any chance to taste this feature with nulls in the nearest future. I'm using Klaxon in KotlinDL library and I've bumped from 5.0.4 to 5.4 and now it's a huge problem for me. Are you going to release klaxon in the nearest 1-2 months? Thanks
