### ISSUE TITLE
FileReaders are not closed

### ISSUE THREAD

**Issue by Octogonapus** [cbeust/klaxon#259]
### Description

Some methods, like `Klaxon.parse`, which create a `FileReader` never close it. This means that you are no longer able to delete the file which Klaxon opened. In my case, that meant JUnit was unable to delete its `TempDir` on Windows CI builds.

### Steps to Reproduce

1. Call `inline fun <reified T> parse(file: File): T?` from file `Klaxon.kt` with a `File`
2. Try to delete the file.

**Expected behavior:** I should be able to delete the file because it should not be open.

**Actual behavior:** Klaxon never closes the `FileReader` it creates inside of `parse()`, so the file is still open.

### Version

Klaxon 5.0.5

### Additional Information

The workaround for this is simple: give Klaxon a `FileReader` instead of letting it make one so that you can close it yourself.

**Comment by Octogonapus** [comment]
The fix is quite simple (just need to call `use` on the `FileReader`), so I am happy to PR it if it would be accepted.

**Comment by cbeust** [comment]
I'll gladly accept a PR!
