### ISSUE TITLE
Polymorphic Classes example does not work

### ISSUE THREAD

**Issue by Kordishal** [cbeust/klaxon#261]
I would like to use polymorphic classes to parse data values from the Wikidata json dump. Using polymorphic fields is not possible, because it is either a simple string or an JSON Object. 

But I seem unable to actually make it work.

When I simply copy the example from the README it does not compile, because it expects a type parameter for the Shape class when extending the data classes.

I tried to fix it by simply giving it the hard coded string, but then it is not able to actually parse the thing. I also tried giving it an extra type. 

I know that it kind of works but I can't get it to parse an object. The example parses most of it but then gives the following error: 

`Unable to instantiate Snak with parameters [property: P1151, datatype: wikibase-item, snakType: value, dataValue: WikibaseEntityId(value=WikibaseEntityIdValue(entityType=item, numericId=6342720))]`

The problem to me it seems, that it does not know what to do with the actual type definition field.

You can find my code here : https://gist.github.com/Kordishal/3ec5dbb8102d3b5f01abb9bf0807c57f

And the example here: https://gist.github.com/Kordishal/06701fc8921ff73bbe63bcaf5de833c9

Am I just doing it wrong or missing something?

**Comment by cbeust** [comment]
Can you elaborate which part of the documentation is not working?

-- 
Cédric

**Comment by Kordishal** [comment]
This one:

Polymorphic classes

A polymorphic class is a class whose actual type is defined by one of its own properties. Consider this JSON:

[
    { "type": "rectangle", "width": 100, "height": 50 },
    { "type": "circle", "radius": 20}
]

The content of the field type determines the class that needs to be instantiated. You would model this as follows with Klaxon:

@TypeFor(field = "type", adapter = ShapeTypeAdapter::class)
open class Shape(val type: String)
data class Rectangle(val width: Int, val height: Int): Shape()
data class Circle(val radius: Int): Shape()

The type adapter is as follows:

class ShapeTypeAdapter: TypeAdapter<Shape> {
    override fun classFor(type: Any): KClass<out Shape> = when(type as String) {
        "rectangle" -> Rectangle::class
        "circle" -> Circle::class
        else -> throw IllegalArgumentException("Unknown type: $type")
    }
}

The compile tells me to initialize the Shape with the type param.

**Comment by cbeust** [comment]
You're right! Fixed now. Thanks!
