### ISSUE TITLE
JsonObjectConverter throws exception even if it found a suitable contructor.

### ISSUE THREAD

**Issue by VladYagl** [cbeust/klaxon#270]
If one of constructors fails this throws exception no matter what. It probably should throw only if all constructors failed.

https://github.com/cbeust/klaxon/blob/929bff13220ace2288ab94c993d4efce7b7d968a/klaxon/src/main/kotlin/com/beust/klaxon/JsonObjectConverter.kt#L93

**Comment by sghpjuikit** [comment]
The error check defeats the purpose of the constructor iterator.

**Comment by cbeust** [comment]
Fixed in 5.0.11.
