### ISSUE TITLE
It is not possible to parse map with number keys 

### ISSUE THREAD

**Issue by LukasForst** [cbeust/klaxon#276]
Latest klaxon version.

It is not possible to parse map where the keys are numbers. The parser does not fail and returns object that seems to be ok, but when I tried to use the values, I got cast exception. `java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number`
```kotlin
val expected: Map<Int, String> = mapOf(1 to "hello", 2 to "world")

val jsonified = Klaxon().toJsonString(expected)

val actual: Map<Int, String> = Klaxon().parse<Map<Int, String>>(jsonified) ?: fail("Parser failed")

expected.keys.all { expected[it] == actual[it] } // this throws exception
```
Also, in the debugger, it is clear, that keys are strings.
![image](https://user-images.githubusercontent.com/14038818/60494276-c54e5b00-9cae-11e9-9d5d-8bc64e9e3462.png)

JSON then looks like 
```JSON
{
	"1": "hello",
	"2": "hello world"
}
```

Expected behavior would be either to return valid map, null or fail and throw exception.

Update: 
Jackson works correctly.
```kotlin
val mapper = jacksonObjectMapper()
val expected: Map<Int, String> = mapOf(1 to "hello", 2 to "world")
val jsonified = mapper.writeValueAsString(expected)
val actual: Map<Int, String> = mapper.readValue(jsonified)

assert(expected.keys.all { expected[it] == actual[it] })
assert(actual.keys.all { expected[it] == actual[it] })
```

**Comment by nhalase** [comment]
I also ran into this issue. It's because of Type erasure with `Map` at runtime. I worked around it with a [`fieldConverter`](https://github.com/cbeust/klaxon#jsonvalue) on the `Map` with a non-string type.

```kotlin
override fun fromJson(jv: JsonValue): Any? {
    return when (jv.propertyKClass!!.arguments[0].type) {
        Int::class.createType() -> intMapFromJson(jv = jv)
        CustomClass::class.createType() -> customClassFromJson(jv = jv)
        else -> throw KlaxonException("failed to parse ${jv.type}")
    }
}
```

**Comment by cbeust** [comment]
Your original test passes right away for me:
```
@Test
class Issue276Test {
    fun test() {
        val expected: Map<Int, String> = mapOf(1 to "hello", 2 to "world")
        val jsonified = Klaxon().toJsonString(expected)
        val actual: Map<Int, String> = Klaxon().parse<Map<Int, String>>(jsonified) ?: fail("Parser failed")

        expected.keys.all { expected[it] == actual[it] } // this throws exception
    }
}
```

```
===============================================
Default Suite
Total tests run: 1, Failures: 0, Skips: 0
===============================================
```

Are you using the latest Klaxon?

**Comment by cbeust** [comment]
Well actually no, `actual` is different from `expected`. Klaxon did indeed turn the keys into strings.

**Comment by cbeust** [comment]
So the question is: is that wrong?

In strict JSON, keys need to be surrounded with double quotes, the question is: should Klaxon try to understand what's in these double quotes and try to cast it to something different than a string?

For example, should:

```
  { "true": 42 }
```

Map to `Map<Boolean, Int>` or `Map<String, Int>`?

I think magical conversions are dangerous so I prefer to stick to the current behavior. The user can always transform that map into what they really want after JSON parsing.
```

**Comment by LukasForst** [comment]
Well I would say, that when you want `Map<Int, String>` you should get it, or the exception should be thrown/null returned.
