### ISSUE TITLE
jcenter version

### ISSUE THREAD

**Issue by Aoi-hosizora** [cbeust/klaxon#288]
Could author please update the newest version (5.1) to jcenter?

I want to use the `@Json(index)` annotation to preserve the field order. Thx

![image](https://user-images.githubusercontent.com/31433480/66749015-48409d80-eebb-11e9-90cf-61ec0bb9e59d.png)

**Comment by cbeust** [comment]
Done:  https://jcenter.bintray.com/com/beust/klaxon/5.1/
