### ISSUE TITLE
Why is the class Klaxon not a object?

### ISSUE THREAD

**Issue by LartyHD** [cbeust/klaxon#289]
It would be more efficient.

**Comment by cbeust** [comment]
Really? Can you qualify this? More efficient in what measurable ways?

**Comment by LartyHD** [comment]
If u use the `object` keyword instead of `class` so Kotlin will generate a Singleton so you don't need many instances of the class and can use `ClassName` instead of `ClassName()`.

Oh and sorry for this bad sentences, i am not a natural speaker.

**Comment by cbeust** [comment]
The `Klaxon` object has some state associated to it (converters, etc...) so it makes sense to make it instance based instead of static based.

**Comment by LartyHD** [comment]
Wenn has `Klaxon` any state?
I can't find it (i only find functions) and u can use inheritance also in `object`'s.

**Comment by cbeust** [comment]
Converters, property strategies, etc...
