### ISSUE TITLE
Compatibility issue with Java 1.7

### ISSUE THREAD

**Issue by rodrigosalinas** [cbeust/klaxon#33]
Hi,

I tried to use your library in my Android project with this configuration:

```
compileSdkVersion 23
    buildToolsVersion "23.0.2"
    defaultConfig {
        applicationId "blah"
        minSdkVersion 21
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
```

When I try to build I get the error:

```
Error:com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
```

The problem according to Google was some library compiled for Java 1.8. I removed klaxon of my gradle file and my code compiled with no problem.

Suggestions? Thanks in advance.

**Comment by cbeust** [comment]
Yes, I made a mistake with the latest version, I will try and release a 1.7 compatible version as soon as I can.

**Comment by rdavison** [comment]
As of right now, the latest version is 0.24.  I had to go back to version 0.22 in order to get it to work.

**Comment by CapnSpellcheck** [comment]
Still an issue. If I try to use 0.22, I face a different problem: compiled with an incompatible version of Kotlin, probably pre-1.0...

**Comment by CapnSpellcheck** [comment]
If we can't have a build soon, can I make a build for myself that is Java 1.7 compatible? Is it just a build setting? It's been a few years since I've worked on Java. I remember that javac has -target option, I thought in IDEA it was 'language level', which seems to be 6 when I open the project.

**Comment by CapnSpellcheck** [comment]
By just including the sources in project directly, it's easy to get working. And no additional cost to the binary. Only tedium would be having to reinsert new versions.

**Comment by aem** [comment]
Hi, is there an update on this? Would love a 1.7-compatible version

**Comment by cbeust** [comment]
I just deployed 0.28 to JCenter, which should be 1.7 compatible (not 100% sure though).

Please try it and report back.

Thanks!

**Comment by aem** [comment]
Getting close! I'm now getting an error that it was compiled with a pre-release version of Kotlin. Looks like the Kotlin version in the pom.xml is still 0.12

**Comment by cbeust** [comment]
Ah yes, I'm using Kotlin 1.1.0. I just deployed 0.29, which should be
compiled with Kotlin 1.0.6.


-- 
Cédric

**Comment by aem** [comment]
still getting the same pre-release error on 0.29

**Comment by cbeust** [comment]
Mmmh, there still must be 1.1.0 dependencies that got pulled.

Can you invoke the Kotlin compiler with `-Xskip-metadata-version-check`, as the error message should have suggested?

**Comment by aem** [comment]
I'm building with gradle (and unfortunately I don't have much gradle experience, I'm new to the project) so I'm not entirely sure how to pass the argument in to the compiler

**Comment by cbeust** [comment]
I'm not sure either and I couldn't find a quick answer. Either way, Kotlin 1.1 RC has just been announced so 1.1 will come out soon, so all this will be moot.

**Comment by aem** [comment]
Yep, saw that. And we're not building the feature that would depend on this for a couple of weeks anyway, so by the time the RC gets releases as stable we should all be good

**Comment by robmoore** [comment]
Not sure if this is a separate issue but I'm seeing the same error using Java 1.8 and Kotlin 1.1.

```
e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
e: /home/rob/Work/IdeaProjects/vault-scripts/src/main/kotlin/com/epatientfinder/dorothy/allscripts.kt: (5, 25): Class 'com.beust.klaxon.Parser' is compiled by a pre-release version of Kotlin and cannot be loaded by this version of the compiler
e
```

**Comment by cbeust** [comment]
I just deployed 0.30, compiled with Kotlin 1.1.0. Can you try again?

**Comment by robmoore** [comment]
That works. Thanks!
