### ISSUE TITLE
Using a model class for parsing

### ISSUE THREAD

**Issue by PierBover** [cbeust/klaxon#34]
Is this possible with Klaxon?

Maybe I'm missing something, but from the examples on the README it seems you have to manually parse each property to a variable.

**Comment by fboldog** [comment]
Yes, unfortunately you don't miss anything.

But with a little extension, you can do.
```kotlin
inline fun <T> JsonObject.objectFromFunction(function: (JsonObject) -> T): T = function(this)
```

```kotlin
    val objParser: (JsonObject) -> XYZFunObj = { obj ->
        XYZFunObj(
            id = obj.string("id")!!,
            name = obj.string("name")!!,
            text = obj.string("text"),
            xyzenum = obj.enum<XYZEnum>("xyzenum"),
            funobj = obj.obj("funobj").objectFromFunction(funobjParser),
            ion = obj.intOrNull("ion"),
            zyzobj = obj.array<XYZObj>("xyzobj").orEmpty().toTypedArray(),
        )
    }
```

and if you have a array of XYZFunObj:
```kotlin
val objects = parser.map { obj -> obj.objectFromFunction(objParser) }.toList()
```

**Comment by PierBover** [comment]
Thanks, for the suggestion. Seems a bit convoluted for something that should much more simple.

**Comment by cbeust** [comment]
@PierBover Agreed, it's just that in this first iteration for Klaxon, my design goal was simply to make it a JSON parser. Object binding would need to be built on top of it, and it would probably be pretty easy.

**Comment by ddmytrenko** [comment]
@cbeust are you still planning to build that object binding on top of Klaxon? ;)

**Comment by cbeust** [comment]
I'm open to it although it feels like it should be a separate library built on top of Klaxon. I'm guessing you are talking about using annotations and writing serializer/deserializers to automatically map between JSON and your objects?

**Comment by ddmytrenko** [comment]
@cbeust Exactly! You are right. It will be much more useful and lets say production ready. It is pretty hard to use Klaxon w/o this feature with Retrofit for example.

**Comment by cbeust** [comment]
Can you give an example of the kind of code + annotations you'd like to see? There are plenty of similar libraries out there already, I don't want to reinvent something completely from scratch.

**Comment by ddmytrenko** [comment]
Yes, we do not need to reinvent the wheel. We can use reflection the way other libs do.

**Comment by cbeust** [comment]
FYI I started looking into this, you can find my current thinking in `master` (see [BindingTest.kt](https://github.com/cbeust/klaxon/blob/master/src/test/kotlin/com/beust/klaxon/BindingTest.kt) ).

This is still very temporary, I'm still fleshing out the API in my head.

I'm also trying to figure out the best API possible to have both type adapters (apply to every single instance of that type) and field adapters (uses an annotation and uses a specific type adapter just for a specific field).

The current API is strongly inspired from Moshi but I'm beginning to deviate from it in places.

Suggestions welcome.

**Comment by cbeust** [comment]
I'm almost done adding object binding to Klaxon. I don't have a documentation yet but here are the current tests:

https://github.com/cbeust/klaxon/blob/master/src/test/kotlin/com/beust/klaxon/BindingAdapterTest.kt
https://github.com/cbeust/klaxon/blob/master/src/test/kotlin/com/beust/klaxon/BindingTest.kt

Feedback welcome.

**Comment by cbeust** [comment]
Klaxon 2.0.0 RC is now [available on JCenter](http://jcenter.bintray.com/com/beust/klaxon/2.0.0-RC1/).

[Updated doc](https://github.com/cbeust/klaxon).

**Comment by cbeust** [comment]
2.0.0 is now released on JCenter.
