### ISSUE TITLE
DSL doesn't work like it is shown in the doc?

### ISSUE THREAD

**Issue by CapnSpellcheck** [cbeust/klaxon#39]
I'm trying to use the DSL with kt 1.0.4 and I get compile error with use of obj:
`            val json: JsonObject = com.beust.klaxon.json { obj("id", "1") }`

> Error:(49, 64) Type mismatch: inferred type is String but Pair<String, *> was expected

Maybe it doesn't work like that anymore?

**Comment by cbeust** [comment]
Indeed, use `to` to associate values to keys:

```
val json: JsonObject = com.beust.klaxon.json { obj("id" to "1") }
```

**Comment by cbeust** [comment]
I updated the doc. Thanks!

**Comment by CapnSpellcheck** [comment]
Got it, thanks!
 

    On Thursday, September 29, 2016 9:57 AM, Cedric Beust <notifications@github.com> wrote:
 

 Indeed, use to to associate values to keys:val json: JsonObject = com.beust.klaxon.json { obj("id" to "1") }
