### ISSUE TITLE
Add ability to output ordered json

### ISSUE THREAD

**Issue by lehmanju** [cbeust/klaxon#48]
For a custom project utilizing json I would appreciate having an operation that outputs alphabetically ordered json. This is needed to add a signature to it and to verify that signature afterwards.
It is therefore important that underlying maps are sorted recursively. I think the easiest solution to achieve that is to use Kotlin's standard operation ```toSortedMap()``` which, unfortunately, does not sort recursively.

**Comment by cbeust** [comment]
Might as well be more general and let the user specify an ordering function for the fields.
