### ISSUE TITLE
Maven distribution

### ISSUE THREAD

**Issue by jvelo** [cbeust/klaxon#5]
Hi,

I could not find a maven repository with klaxon releases. Is distribution planned ?

Thanks

**Comment by cbeust** [comment]
Yes, I'm planning on doing that. Until then, you can use https://jitpack.io/

**Comment by cbeust** [comment]
Hi Jérôme,

Klaxon is now available on JCenter, can you give it a shot and report back?

```
repositories {
    jcenter()

}

dependencies {
    compile 'com.beust:klaxon:0.12'
}
```

**Comment by jvelo** [comment]
Hi Cédric,

Thanks a lot, it works great.
