### ISSUE TITLE
Can someone write an updated exemple code ?

### ISSUE THREAD

**Issue by mtrelis** [cbeust/klaxon#51]
Hello,
I'm trying out the exemple that's written in the read.md but I get errors everywhere
"Parser is deprecated"
"Type mismatch, found Any? required : Any"
"A 'return' expression required in a function with a block body ('{...}')"
and so on

can someone help ?

**Comment by cbeust** [comment]
Can you be more specific and show the code where these errors are?

**Comment by damphat** [comment]
updated! https://github.com/cbeust/klaxon/pull/50/commits/158d97ec35c475064b9556961038b80a30a34803
