### ISSUE TITLE
Klaxon with Anko's doAsync fails to execute

### ISSUE THREAD

**Issue by mtrelis** [cbeust/klaxon#52]
Hello !
I'm trying to parse an url whenever I press a button :

```
    button.setOnClickListener {
doAsync{
    val result = URL("http://date.jsontest.com/").readText()
    val parser: Parser = Parser()
    val stringBuilder: StringBuilder = StringBuilder(result)
    val json: JsonObject = parser.parse(stringBuilder) as JsonObject
    val time = "Time : ${json.string("time")}"
uiThread { textView.setText(time) }}}
```
But I'm getting an error :

> Error pruning approved print services. java.util.concurrent.TimeoutException: Cannot get spooler!

What is wrong ?

**Comment by damphat** [comment]
Not a `klaxon` issue. You should post question like this on SO.

The code above should work with proper version of Android Framework, Anko library and INTERNET permission.
