### ISSUE TITLE
Are there any Proguard considerations?

### ISSUE THREAD

**Issue by CapnSpellcheck** [cbeust/klaxon#53]
This is just a question. When I build an APK with a `minifyEnabled true` I get warnings:

> Note: the configuration keeps the entry point 'letstwinkle.com.twinkle.model.ConnectionProfile { ConnectionProfile(com.beust.klaxon.JsonObject); }', but not the descriptor class 'com.beust.klaxon.JsonObject'

I am very green with Proguard. When I expose types of a library such as klaxon in my API. Is it up to me to manage Proguard rules for this? Are there any specific rules you can recommend?

SHould I just keep everything in com.beust.klaxon, what would a rule for that look like? I'd like to keep it simple, I'm sure this library does not have code bloat ;)

**Comment by cbeust** [comment]
Not quite sure what this message means, you might want to ask on the Proguard forums... Feel free to reopen if there's anything I need to do on the Klaxon side.
