### ISSUE TITLE
Bad method signature for string parsing.

### ISSUE THREAD

**Issue by Querschlag** [cbeust/klaxon#55]
I found the signatures for parsing raw strings to be a little confusing.
When I try to parse a raw string I kind of expect to use the parser like that:
```
Parser().parse(myString)
```
The problem is that the parse method which accepts a string uses it to load a file instead of directly processing it.
```
fun parse(fileName: String)
```
So when I want to parse a raw string i have to wrap it in a StringBuilder instance, which is not nice.
```
Parser().parse(StringBuilder(myString))
```
From my perspective `parse()` should treat a string argument as a raw string value and directly parse it.
I know it might be problematic to change the behaviour of `fun parse(fileName: String)`, but the current implementation is far from ideal.

**Comment by cbeust** [comment]
Klaxon 2.0 has been adjusted to do just that: `parse(String)` takes a JSON string (and other parameters in its overloaded variants).
