### ISSUE TITLE
Parse String is missing.

### ISSUE THREAD

**Issue by ppamorim** [cbeust/klaxon#57]
Currently this library parse a StringBuilder`fun parse(rawValue: StringBuilder): Any? {}`. Why? If it uses the reference as a internal reader, it needs to be completed internal (the reference). It also needs to accept a String.

**Comment by ppamorim** [comment]
https://github.com/cbeust/klaxon/issues/55

**Comment by cbeust** [comment]
`parse()` currently accepts many parameters, including `String` and `Reader`.
