### ISSUE TITLE
Remove optional fields

### ISSUE THREAD

**Issue by ppamorim** [cbeust/klaxon#58]
Optional fields are not necessary on this library, would be great to unwrap it on the backend and leave the developer to choose the default parameter. Today to have a default parameter the developer needs to do this:
```Kotlin
jsonObject.int("value") ?: 0 //Return Int?
```
This provides a inconsistent and complexbility, something like this would be better:
```Kotlin
jsonObject.int("value", default = 0) //Return Int
```
I think to maintain both methods, if the user wants to use the default reader, there is no problem.

**Comment by cbeust** [comment]
I think the `?:` syntax is more idiomatic so why reinvent this mechanism in Klaxon?
