### ISSUE TITLE
Empty StringBuilder causes No state found: INIT EOF

### ISSUE THREAD

**Issue by ppamorim** [cbeust/klaxon#62]
Hi guys

I was doing unit test on my application and I discovered that sending a empty StringBuilder causes a crash. I think that you be good to detect it before start the parsing and then, return a empty `JsonObject` or `JsonArray`.

**Comment by damphat** [comment]
Hi @ppamorim 

According to http://www.json.org, empty string is not a valid json.
```
> JSON.parse("")
SyntaxError: Unexpected end of JSON input
```

If you want to add **non-strict mode** for klaxon then the Parser should return **null** for empty string.

**Comment by ppamorim** [comment]
@damphat Null means anything, we need to find a better solution for that fallback. Maybe returning `Nothing`?

**Comment by haskellcamargo** [comment]
The behavior is correct, @ppamorim.
According to any JSON RFC specification, the first entry must be a JSON-valid expression. Empty string is a syntax error. No matches for `"`, `{`, `[`, `\d`, `true`, `false` or any other valid start token.

**Comment by ppamorim** [comment]
@haskellcamargo The behavior is correct but the way that the library currently handles the exception doesn't help. Returning a `null` or `nothing` can be better.

**Comment by haskellcamargo** [comment]
Almost every parser of JSON will throw unexpected end of input. A JSON parser will look for a valid start token, such as `STRING`, `TRUE`, `FALSE`, `OPEN_BRACE`, `OPEN_BRACKET` or `QUOTE`. But, in that case, after trying all these, the found token was `EOF`, therefore it was *unexpected*.

It's default behavior, as you can see on JavaScript's default Chrome implementation.
![2017-08-18-165305_374x97_scrot](https://user-images.githubusercontent.com/7553006/29475351-ba44b99a-8435-11e7-9013-a737a7e532a2.png)

**Comment by damphat** [comment]
parse("") **MUST** return an error.

WHY?
There are a lot of projects that depends on **klaxon**, they may use that Exception for detecting error, validate user input, etc.

Even if you want to return **null**, you must explicitly provide an option for example:
```kotlin
val parser = Parser(Parser.NonStrict)
parser.parse("") // return null
```

**Comment by ppamorim** [comment]
It can use a clear Exception for a strict configuration, it's more sensible. I noticed that the parser does a lot of verification/setup and then thrown the error. Is that correct?

**Comment by ppamorim** [comment]
@damphat I did changes on my pull request. Would you like to have a look on it? Thank you.
