### ISSUE TITLE
getting array from empty value

### ISSUE THREAD

**Issue by coyool** [cbeust/klaxon#64]
{
"from":"inpatient",
"department":"ADT",
"phototype":"PATHO",
"bodypart":"&nbsp;",
"time":"2016/12/2 15:33:39",
"piclink":"",
"reportlink":["/BGData/DJ201612J/DJ20161201J0515/BG20161202004800.jpg","/BGData/DJ201612J/DJ20161201J0515/BG20161202004801.jpg"]
}

I think when getting the piclink as an array of strings, it should return an empty array instand of throwing an error,(test on ver 0.30)

**Comment by ppamorim** [comment]
At first, would you like to be more clear explaining what is your problem?

If I am not wrong, this is a correct behavior but not the best, a empty `Array` needs to be an `Array` type, if the server returns a empty value and the object is an `Array`, a error will happen. This is a common behavior of any JSON mapper.
We are working to make it more sensible you can choose if you want to return `null` or a explained `Exception`. But for now you can dig this problem reading the value as `String`, verifying if the value is an `Array` and then, parse the `Array`.

**Comment by coyool** [comment]
this jsong string is created by node-js std libs, I means "an empty array" is better , compare to  "null" or Exception
