### ISSUE TITLE
double accessor not numeric-friendly like int/long accessors

### ISSUE THREAD

**Issue by CapnSpellcheck** [cbeust/klaxon#66]
I have a need for a floating point field in a JSON object.

In my mind, '0' is a valid double as well, and certainly may be returned from my backend along with '1.2345'. However, JsonObject::double does not play nicely with other Number types like JsonObject::long for some reason.

Does it make sense to change this?

**Comment by cbeust** [comment]
If this is valid JSON, sure.


-- 
Cédric

**Comment by CapnSpellcheck** [comment]
This seems to be a workaround: ` (json["lat"] as Number).toDouble()`

**Comment by cbeust** [comment]
Indeed. Ok to close?

**Comment by CapnSpellcheck** [comment]
It could be a stumbling block for people, especially since it could crash
an unwary application.

**Comment by fboldog** [comment]
@CapnSpellcheck i wrote a little extension for Klaxon long time ago: https://github.com/fboldog/ext4klaxon 
which is support this.

**Comment by CapnSpellcheck** [comment]
Why don't you have a floating point?? 👎 

I need to support an int converted to float or double, not the other way around.
