### ISSUE TITLE
New release needed

### ISSUE THREAD

**Issue by fluidsonic** [cbeust/klaxon#67]
Hey guys,

this is a great library!
Unfortunately the latest release was a while ago and critical fixes like #47 are yet to be released.
Can you please publish a new version?

Thanks!

**Comment by cbeust** [comment]
Done, [0.32](http://jcenter.bintray.com/com/beust/klaxon/0.32/) is now available on JCenter.

**Comment by fluidsonic** [comment]
Amazing speed, thank you! ❤️
