### ISSUE TITLE
String gets trimmed?

### ISSUE THREAD

**Issue by dimaklt** [cbeust/klaxon#68]
My Json String in RecyclerView - CardView is getting trimmed and I can't figure out why.

Json:
`[ ... {`
`     "witz":"Fritzchen: \"Darf ich ins Schwimmbad? Das 3m-Brett wird eröffnet.\"\n\nMutter: \"Ja.\"\n\nFritzchen kommt mit einem gebrochenem Bein zurück.\n\nAm nächstem Tag: \"Mutti darf ich ins Schwimmbad? Das 10m-Brett wird eröffnet.\"\n\nMutter: \"Ja.\"\n\nFritzchen kommt mit zwei gebrochenen Beinen zurück.\n\nAm nächsten Tag: \"Mutti darf ich ins Schwimmbad? Das Wasser wird eingelassen.\""`
`  }, ... ]`

Code:
`val array = Parser().parse(resources.openRawResource(id)) as JsonArray<*>`

`recyclerView = view.find(R.id.recycler_view)`
`recyclerView?.layoutManager = LinearLayoutManager(context)`
`recyclerView?.adapter = MainAdapter(`
`context,`
`        (0 until array.size).map { """${array["witz"][it]}""" },`
`        (0 until array.size).map { """${getString(R.string.id_count)} ${it + 1}/${array.size}""" }`
`)`

Output:
`Fritzchen: "Darf ich ins Schwimmbad? Das 3m-Brett wird eröffnet."`

`Mutter: "Ja."`

**Comment by cbeust** [comment]
Should be fixed in `master`.
