### ISSUE TITLE
Parser deprecated warning

### ISSUE THREAD

**Issue by Logmytech** [cbeust/klaxon#70]
I'm getting a `Parser` is deprecated in Java or something error. 

I supressed the error and am recalling from memory. 

Is this normal or something I should be worried about?

I found this page https://docs.oracle.com/javase/7/docs/api/org/xml/sax/Parser.html

```This interface has been replaced by the SAX2 XMLReader interface, which includes Namespace support.```

**Comment by cbeust** [comment]
Wrong `Parser`.
