### ISSUE TITLE
Interface Parser does not have constructors

### ISSUE THREAD

**Issue by Logmytech** [cbeust/klaxon#71]
I have copied and pasted the function for converting to JSON and I get the above error.

`Interface Parser does not have constructors`

I have pasted the following code from `Reademe.md`

```
fun parse(name: String) : Any? {
            val cls = Parser::class.java
            return cls.getResourceAsStream(name)?.let { inputStream ->
                return Parser().parse(inputStream)
            }
        }
```

**Comment by cbeust** [comment]
Are you sure you're using the right `Parser`? Please post your `imports`.

**Comment by Logmytech** [comment]
Turns out I was importing another Java library containing Parser.
