### ISSUE TITLE
what is bad?

### ISSUE THREAD

**Issue by mhsystem** [cbeust/klaxon#72]
val stringBuilder: StringBuilder = StringBuilder(request.toString())
and I see Expected a value type Any!

**Comment by cbeust** [comment]
How is this related to Klaxon?

**Comment by mhsystem** [comment]
val parser: Parser = Parser()
val stringBuilder: StringBuilder = StringBuilder("{\"name\":\"Cedric Beust\", \"age\":23}")
val json: JsonObject = parser.parse(stringBuilder) as JsonObject
println("Name : ${json.string("name")}, Age : ${json.int("age")}")

and I see Expected a value type Any!
