### ISSUE TITLE
Can't parse "Long" type

### ISSUE THREAD

**Issue by asteinba** [cbeust/klaxon#75]
Hi guys,
is parsing to the "Long" type not supported in the high level API?

The following does not work with 2.0.0-RC1:
```
Klaxon().parse<TestObj>(""" {"id": 53147483640 } """)
data class TestObj(var id: Long? = null)  
```

not even with a 32bit number:
```
Klaxon().parse<TestObj>(""" {"id": 234 } """)
data class TestObj(var id: Long? = null)  
```

Thanks!

**Comment by cbeust** [comment]
Good catch. This should be fixed in [2.0.0-RC2](http://jcenter.bintray.com/com/beust/klaxon/2.0.0-RC2/).

**Comment by asteinba** [comment]
Awesome, thanks for the quick response + fix. I really enjoy your library and hope I can contribute when I get more comfortable using Kotlin.

**Comment by cbeust** [comment]
Thanks! Don't hesitate to provide feedback on the new object binding API (and feel free to reach out to me directly on the kotlinlang Slack).
