### ISSUE TITLE
DecimalFormat exception

### ISSUE THREAD

**Issue by dibenlloch** [cbeust/klaxon#81]
Hi, there is some exception in this line that crashes every toJsonString invoke

https://github.com/cbeust/klaxon/blob/c5a282e026cb8e13f822ca91cff0e0b43a693aa7/src/main/kotlin/com/beust/klaxon/Render.kt#L36

java.lang.IllegalArgumentException: Unquoted special character '#' in pattern "0.0####E0##;-0.0####E0##"

**Comment by cbeust** [comment]
Can you provide the JSON you're trying to parse?

**Comment by dibenlloch** [comment]
all json, also evaluating DecimalFormat("0.0####E0##;-0.0####E0##") in console thows me exception

**Comment by cbeust** [comment]
I have quite a few tests using various decimal formats that pass, so not all JSON trigger that bug.

Just paste the JSON or object you're using so I can reproduce the bug.

Thanks.

**Comment by dibenlloch** [comment]
For example

```
                    val parser: Parser = Parser()
                    val stringBuilder: StringBuilder = StringBuilder("{\"name\":\"Cedric Beust\", \"age\":23}")
                    val json: JsonObject = parser.parse(stringBuilder) as JsonObject
                    json.toJsonString()
```

**Comment by cbeust** [comment]
Passes for me:

```
===============================================
Default Suite
Total tests run: 1, Failures: 0, Skips: 0
===============================================
```

**Comment by cbeust** [comment]
I'm puzzled, are you trying to build Klaxon? If you are, do the tests pass for you?

**Comment by dibenlloch** [comment]
No i'm using library com.beust:klaxon:2.0.7

**Comment by cbeust** [comment]
Can you paste your stack trace?

**Comment by dibenlloch** [comment]
`                         E  java.lang.ExceptionInInitializerError
                         E      at com.beust.klaxon.RenderKt.renderValue(Unknown Source:0)
                         E      at com.beust.klaxon.JsonObject.appendJsonStringImpl(DSL.kt:46)
                         E      at com.beust.klaxon.JsonBase$DefaultImpls.appendJsonString(DSL.kt:13)
                         E      at com.beust.klaxon.JsonObject.appendJsonString(DSL.kt:21)
                         E      at com.beust.klaxon.JsonBase$DefaultImpls.toJsonString(DSL.kt:15)
                         E      at com.beust.klaxon.JsonObject.toJsonString(DSL.kt:21)
                         E      at com.beust.klaxon.JsonBase$DefaultImpls.toJsonString$default(DSL.kt:14)
                         E      at com.wefox.sdk.app.blocks.chatbot.ChatBotActivity.openCompare(ChatBotActivity.kt:183)
                         E      at com.wefox.sdk.app.blocks.chatbot.ChatBotPresenter.sendMessage(ChatBotPresenter.kt:142)
                         E      at com.wefox.sdk.app.ui.inputs.ComparePolicy.onClick(ComparePolicy.kt:47)
                         E      at android.view.View.performClick(View.java:6256)
                         E      at android.view.View$PerformClick.run(View.java:24701)
                         E      at android.os.Handler.handleCallback(Handler.java:789)
                         E      at android.os.Handler.dispatchMessage(Handler.java:98)
                         E      at android.os.Looper.loop(Looper.java:164)
                         E      at android.app.ActivityThread.main(ActivityThread.java:6541)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                         E  Caused by: java.lang.IllegalArgumentException: Unquoted special character '#' in pattern "0.0####E0##;-0.0####E
                            0##"
                         E      at android.icu.text.DecimalFormat.patternError(DecimalFormat.java:5171)
                         E      at android.icu.text.DecimalFormat.applyPatternWithoutExpandAffix(DecimalFormat.java:4894)
                         E      at android.icu.text.DecimalFormat.createFromPatternAndSymbols(DecimalFormat.java:704)
                         E      at android.icu.text.DecimalFormat.<init>(DecimalFormat.java:693)
                         E      at java.text.DecimalFormat.init(DecimalFormat.java:470)
                         E      at java.text.DecimalFormat.<init>(DecimalFormat.java:438)
                         E      at com.beust.klaxon.RenderKt.<clinit>(Render.kt:38)
                         E      ... 19 more
`

**Comment by cbeust** [comment]
Sounds like Android's `DecimalFormat` differs from the JDK's...

**Comment by cbeust** [comment]
It's working fine in the IDEA REPL:

![image](https://user-images.githubusercontent.com/92322/34954171-4b646416-f9d4-11e7-801d-99afcf9bbd2c.png)

What console are you trying it in? Android Studio?

By the way, feel free to message me directly in the Kotlin Slack if you prefer.

**Comment by dibenlloch** [comment]
Ok, we can continue from kotlin slack , i'm using Android studio
