### ISSUE TITLE
Not resolvin dependecies.

### ISSUE THREAD

**Issue by xinux87** [cbeust/klaxon#88]
Hi the library cannot be resolved on the server.

thanks!

**Comment by cbeust** [comment]
What do you mean?

**Comment by oharaandrew314** [comment]
@xinux87, can you include your build script?  e.g. from maven, gradle, kobalt, etc.

**Comment by leandroBorgesFerreira** [comment]
There is no file for the latest version in Bintray

**Comment by cbeust** [comment]
Oops good catch, not sure what happened. Should be fixed now:

http://jcenter.bintray.com/com/beust/klaxon/2.0.11/

**Comment by oharaandrew314** [comment]
That's strange.  I had 2.0.10
