### ISSUE TITLE
Not escaping quotes or other special characters from String

### ISSUE THREAD

**Issue by vishna** [cbeust/klaxon#91]
correct me if I'm wrong, but seems doing something like this:

```kotlin
val map = HashMap<String, String>()
map["whoops"] = """ Hello "world" """
Klaxon().toJsonString(map)
```

will produce a json output like this:
```json
{"whoops": " Hello "world" "}
```

and it should be:
```json
{"whoops": " Hello \"world\" "}
```

seems the necessary code should to be added here:
https://github.com/cbeust/klaxon/blob/aba50cccc5492ba57bc0946c7e2ebfcc7192b046/src/main/kotlin/com/beust/klaxon/DefaultConverter.kt#L19

**Comment by cbeust** [comment]
Fixed in 2.0.12.
