### ISSUE TITLE
Lazy object parsing

### ISSUE THREAD

**Issue by prestongarno** [cbeust/klaxon#97]
First off, I want to say that I am thoroughly impressed by the refactor, I've been using since 0.3.0 and can't wait to use the latest version!

I'm wondering if it's possible to defer parsing to a JsonObject if requested. My use case is a client I'm building for GraphQL queries. I already have a type hierarchy of custom properties which take care of mapping/validating the resulting values parsed from the JSON response to their corresponding types, but I want to take it a step further and lazily resolve the non-scalar/class instances on the graph via the streaming API.

Example from the docs is:

    var obj1: JsonObject? = null

    while (reader.hasNext()) {
        when (reader.nextName()) {
             "obj1" -> obj1 = reader.nextObject()
        }
    }

Would it be possible to do something like:

    class LazyJsonObject(val name: String,  text: String): Lazy<Map<String, JsonValue> by lazy({
        // parse the json string here
    })

    var obj1: LazyJsonObject? = null

    while (reader.hasNext()) {
        when (reader.nextName()) {
             "obj1" -> obj1 = reader.lazyNextObject()
        }
    }

Or is this already done behind the scenes? I couldn't tell after going through the source for a few minutes.

**Comment by cbeust** [comment]
Thanks for the kind words!

I don't see how that's possible since Klaxon will have to consume that `JsonObject` before it can give you the next name.

Or am I missing something? What are you trying to achieve with this lazy loading? What problem are you trying to solve?

**Comment by prestongarno** [comment]
Its not a priority for me, just thought I'd ask. The idea is to simply return the name and the string representation of the object, so I can parse it later. Each one creates a new `Map` instance, right?

I am resolving property values in arbitrarily large object graphs via custom property delegates and I want to wait until any non-primitive property is accessed to parse it, and do the same for nested json objects or arrays. Although I guess since I already have control over properties it wouldn't be too difficult to write my own parser. 

Or is this impossible to do? I've never done anything with JSON parsing before.

**Comment by cbeust** [comment]
My point is that there is no "parsing later". Assume you have:

```
"a": { object1 }
"b": ...
```

The first name will give you "a" but if you ask for the next name, Klaxon will have to have parsed `object1` before it gives you that next name. So you're not saving any parsing.

**Comment by prestongarno** [comment]
Okay, makes sense. I thought it might be possible to simply read the input stream until the object's closing "}" bracket. That way you defer creation of all of the nested `JsonObjects` until later, and save on stack space. I have no idea what is more expensive, memory or reading bytes. Just an idea, feel free to close this if it doesn't fall under project scope.
