### ISSUE TITLE
How to pretty print data class?

### ISSUE THREAD

**Issue by Nutomic** [cbeust/klaxon#98]
I have some code like this:
```
data class MyClass(val list: List<String>, i: Int)
val obj = MyClass(listOf(), 1)
Klaxon().toJsonString(obj)
```
However, this results in a string without any whitespace or formatting. Is there another call that applies formatting to the output string? The readme recommends `JsonObject.toJsonString()`, but I cant find any way to turn my object into a JsonObject with klaxon.

What is the correct way to do this?

**Comment by cbeust** [comment]
Per [the documentation](https://github.com/cbeust/klaxon#pretty-printing):

> You can convert any JsonObject to a valid JSON string by calling `toJsonString()` on it. If you want to get pretty-printed version then you can call `toJsonString(true)`

**Comment by Nutomic** [comment]
Yes I saw that. My question is, how do I turn my object into a JsonObject? It looks like this code works, but is there no easier option?
```
val sb = StringBuilder(Klaxon.toJsonString(config))
val jsonString = (Parser().parse(sb) as JsonObject).toJsonString(true)
```

**Comment by cbeust** [comment]
No, that's pretty much it.

**Comment by Nutomic** [comment]
Alright, thanks!

**Comment by camdenorrb** [comment]
Why do you first have to convert it to a String......

**Comment by MeLlamoPablo** [comment]
@camdenorrb +1

It would be nice to have

```kotlin
Klaxon().toJsonString(obj, prettyPrint = true)
```

**Comment by camdenorrb** [comment]
@cbeust I'm making a new issue for this

**Comment by BinaryShrub** [comment]
I cant find the new issue @camdenorrb, has it been implemented yet?

**Comment by camdenorrb** [comment]
@BinaryShrub https://github.com/cbeust/klaxon/issues/217
